<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="fsharp/Utility.fs" />
    <Compile Include="fsharp/domain/AAG.fs" />
    <Compile Include="fsharp/elmish/Template.fs" />
    <Compile Include="fsharp/elmish/Endpoint.fs" />
    <Compile Include="fsharp/elmish/Message.fs" />
    <Compile Include="fsharp/elmish/Model.fs" />
    <Compile Include="fsharp/pages/AddAccessPage.fs" />
    <Compile Include="fsharp/pages/AddVertexPage.fs" />
    <Compile Include="fsharp/pages/MainMenuPage.fs" />
    <Compile Include="fsharp/pages/MainPage.fs" />
    <Compile Include="fsharp/transformer/VisJS.fs" />
    <Compile Include="fsharp/Main.fs" />
    <Compile Include="fsharp/Startup.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Bolero" Version="0.*" />
    <PackageReference Include="Bolero.Build" Version="0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.*" />
    <PackageReference Include="System.Net.Http.Json" Version="8.0.*" />
  </ItemGroup>
  <!-- when changing a template .html file the cachces must be deleted manually. -->
  <!-- Otherwise the next `dotnet run` does not include the newest changes  -->
  <Target Name="CleanCache" BeforeTargets="BeforeBuild">
    <Delete Files="./obj/Debug/net8.0/AAG.Client.AssemblyInfoInputs.cache" />
  </Target>
</Project>