name: Deploy to GitHub Pages

on:
  push:
    branches: [ account-access-graphs-deployment ]

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.110
      - run: dotnet restore
        working-directory: bolerodemo/MyApp
      - run: dotnet clean
        working-directory: bolerodemo/MyApp
      - run: dotnet build --no-restore
        working-directory: bolerodemo/MyApp
      - run: ls -la
        if: always()
      - run: tree .
        if: always()
      - run: cat bolerodemo/MyApp/src/MyApp.Client/obj/CssScopes.fs
        if: always()
      - run: sed -i 's/<base href="\/" \/>/<base href="\/account-access-graphs\/" \/>/g' release/wwwroot/index.html
        working-directory: bolerodemo/MyApp
      - run: touch release/wwwroot/.nojekyll
        working-directory: bolerodemo/MyApp
      - run: cp release/wwwroot/index.html release/wwwroot/404.html
        working-directory: bolerodemo/MyApp
      - id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: bolerodemo/MyApp/release/wwwroot/

  deploy-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
