name: Deploy to GitHub Pages

on:
  push:
    branches: [ account-access-graphs-deployment ]

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.110'
      - run: dotnet --list-sdks
      - run: dotnet --list-runtimes
      - run: dotnet publish -c Release -o release -r linux-x64 --self-contained
        working-directory: bolerodemo/MyApp
      # - run: |
      #     apt-get update
      #     apt-get install -y aspnetcore-runtime-8.0 dotnet-sdk-8.0
      #     dotnet publish -c Release -o /app/release src/MyApp.Client/MyApp.Client.fsproj
      # - name: Build Docker Image
      #   run: docker build -t myapp-image .
      #   working-directory: bolerodemo/MyApp
      # - name: Run Publish in Docker
      #   run: |
      #     docker run --rm -v $(pwd):/app myapp-image \
      #     /bin/bash -c "dotnet publish -c Release -o /app/release src/MyApp.Client/MyApp.Client.fsproj"
      #   working-directory: bolerodemo/MyApp
        # working-directory: bolerodemo/MyApp
      - run: sed -i 's/<base href="\/">/<base href="\/account-access-graphs\/">/g' release/wwwroot/index.html
        working-directory: bolerodemo/MyApp
      - run: touch release/wwwroot/.nojekyll
        working-directory: bolerodemo/MyApp
      - run: cp release/wwwroot/index.html release/wwwroot/404.html
        working-directory: bolerodemo/MyApp
      - id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: bolerodemo/MyApp/release/wwwroot/

  deploy-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
